# Generated by Django 3.0.5 on 2020-04-16 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=20, null=True)),
                ('invoice_id', models.CharField(max_length=50, null=True)),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('card_id', models.CharField(max_length=50, null=True)),
                ('settlement_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payme.TransactionStatus'),
        ),
    ]
