# Generated by Django 3.0.5 on 2020-04-17 04:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0002_auto_20200416_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='settlement_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
