# Generated by Django 3.0.5 on 2020-04-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0003_auto_20200417_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
