# Generated by Django 3.0.5 on 2020-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0004_transaction_settlement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TransactionStatus',
        ),
    ]
